/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ApiGenerateReviewRouteImport } from './routes/api/generate-review'
import { Route as ApiSubmitReferralRouteImport } from './routes/api/submit-referral'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateReviewRoute = ApiGenerateReviewRouteImport.update({
  id: '/api/generate-review',
  path: '/api/generate-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitReferralRoute = ApiSubmitReferralRouteImport.update({
  id: '/api/submit-referral',
  path: '/api/submit-referral',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/refer': typeof ReferRoute
  '/review': typeof ReviewRoute
  '/api/generate-review': typeof ApiGenerateReviewRoute
  '/api/submit-referral': typeof ApiSubmitReferralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/refer': typeof ReferRoute
  '/review': typeof ReviewRoute
  '/api/generate-review': typeof ApiGenerateReviewRoute
  '/api/submit-referral': typeof ApiSubmitReferralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/refer': typeof ReferRoute
  '/review': typeof ReviewRoute
  '/api/generate-review': typeof ApiGenerateReviewRoute
  '/api/submit-referral': typeof ApiSubmitReferralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/refer' | '/review' | '/api/generate-review' | '/api/submit-referral'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/refer' | '/review' | '/api/generate-review' | '/api/submit-referral'
  id:
    | '__root__'
    | '/'
    | '/refer'
    | '/review'
    | '/api/generate-review'
    | '/api/submit-referral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReferRoute: typeof ReferRoute
  ReviewRoute: typeof ReviewRoute
  ApiGenerateReviewRoute: typeof ApiGenerateReviewRoute
  ApiSubmitReferralRoute: typeof ApiSubmitReferralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-review': {
      id: '/api/generate-review'
      path: '/api/generate-review'
      fullPath: '/api/generate-review'
      preLoaderRoute: typeof ApiGenerateReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-referral': {
      id: '/api/submit-referral'
      path: '/api/submit-referral'
      fullPath: '/api/submit-referral'
      preLoaderRoute: typeof ApiSubmitReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReferRoute: ReferRoute,
  ReviewRoute: ReviewRoute,
  ApiGenerateReviewRoute: ApiGenerateReviewRoute,
  ApiSubmitReferralRoute: ApiSubmitReferralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
